name: ubuntu-core-desktop-init
version: git
summary: Ubuntu Core Desktop Init
description: |
  Ubuntu Core Desktop Init.
grade: stable
confinement: strict
base: core22
issues: https://github.com/canonical/ubuntu-core-desktop-init/issues
contact: https://github.com/canonical/ubuntu-core-desktop-init/issues
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  ubuntu-core-desktop-init:
    command: bin/ubuntu_init
    environment:
      LOG_LEVEL: debug
    extensions: [gnome]
    plugs:
      - account-control
      - hostname-control
      - locale-control
      - timezone-control

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.6
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  ubuntu-core-desktop-init:
    after: [flutter-git]
    source: .
    source-type: git
    plugin: nil
    override-build: |
      (mv vendor/ubuntu-desktop-provision/packages/subiquity_client . && cd vendor && rm -rf * && git clone https://github.com/sergio-costas/ubuntu-desktop-provision.git && cd ubuntu-desktop-provision && git checkout add-login-on-end && mv ../../subiquity_client packages && cd packages/ubuntu_wizard && flutter pub get)
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      cp $CRAFT_PROJECT_DIR/assets/ubuntu-provision.conf vendor/ubuntu-desktop-provision/packages/ubuntu_init/assets/
      cp $CRAFT_PROJECT_DIR/assets/mascot.png vendor/ubuntu-desktop-provision/packages/ubuntu_init/assets/
      cd vendor/ubuntu-desktop-provision/packages/ubuntu_init
      # work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253
      set +e
      dart pub get
      set -eux
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

slots:
  dbus-name:
    interface: dbus
    bus: session
    name: com.canonical.ubuntu_init
